name: hetmech
channels:
  - conda-forge
dependencies:
  - conda-forge::flake8=3.5.0
  - conda-forge::ipykernel=4.8.1
  - conda-forge::ipywidgets=7.1.1
  - conda-forge::nb_conda_kernels=2.1.0
  - conda-forge::notebook=5.4.0
  - conda-forge::numpy=1.14.0
  - conda-forge::pandas=0.22.0
  - conda-forge::plotnine=0.3.0
  - conda-forge::py2neo=3.1.2
  - conda-forge::pytest=3.4.0
  - conda-forge::python=3.6.4
  - conda-forge::requests=2.18.4
  - conda-forge::scikit-learn=0.19.1
  - conda-forge::scipy=1.0.0
  - conda-forge::tqdm=4.19.5
  - conda-forge::xarray=0.10.0
  - conda-forge::xlrd=1.1.0
  - pip:
    - hetio==0.2.8
    - neo4j-driver==1.5.3
