name: hetmech
channels:
  - conda-forge
dependencies:
  - conda-forge::flake8=3.5.0
  - conda-forge::ipykernel=4.8.2
  - conda-forge::ipywidgets=7.4.0
  - conda-forge::nb_conda_kernels=2.1.1
  - conda-forge::notebook=5.6.0
  - conda-forge::numpy=1.14.6
  - conda-forge::pandas=0.23.4
  - conda-forge::plotnine=0.4.0
  - conda-forge::py2neo=3.1.2
  - conda-forge::pytest=3.7.2
  - conda-forge::python=3.6.6
  - conda-forge::requests=2.19.1
  - conda-forge::scikit-learn=0.19.2
  - conda-forge::scipy=1.1.0
  - conda-forge::tqdm=4.24.0
  - conda-forge::xarray=0.10.8
  - conda-forge::xlrd=1.1.0
  - pip:
    - git+https://github.com/hetio/hetio@ae2d0bce46e7137ae8812e99ce0e8301f8b7fa53
    - neo4j-driver==1.6.1
