name: hetmech
dependencies:
- flake8=3.3.0
- scipy=0.19.0
- scikit-learn=0.18.1
- numpy=1.12.0
- ipykernel=4.5.2
- pandas=0.19.2
- pytest=3.0.6
- python=3.6.0
- pip:
  - neo4j-driver==1.1.2
  - hetio==0.2.4
  - regex
